from exceptions.main import Main

main = Main()


def test_logging_exception():
    main.logging_exception()
